version: "3.8"

services:
  dfapp:
    image: dataformer/dfapp:latest
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - DFAPP_DATABASE_URL=postgresql://dfapp:dfapp@postgres:5432/dfapp
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
      - DFAPP_CONFIG_DIR=/var/lib/dfapp
    volumes:
      - dfapp-data:/var/lib/dfapp

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: dfapp
      POSTGRES_PASSWORD: dfapp
      POSTGRES_DB: dfapp
    ports:
      - "5432:5432"
    volumes:
      - dfapp-postgres:/var/lib/postgresql/data

volumes:
  dfapp-postgres:
  dfapp-data:
