prompts:
  ChatMessagePromptTemplate:
    documentation: ""
  HumanMessagePromptTemplate:
    documentation: ""
  SystemMessagePromptTemplate:
    documentation: ""
  ChatPromptTemplate:
    documentation: ""
  PromptTemplate:
    documentation: ""
wrappers:
  RequestsWrapper:
    documentation: ""
  SQLDatabase:
    documentation: ""
output_parsers:
  StructuredOutputParser:
    documentation: ""
  ResponseSchema:
    documentation: ""
custom_components:
  CustomComponent:
    documentation: ""
    # documentation: "https://docs.dataformer.ai/administration/custom-component"
