prompts:
  ChatMessagePromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/prompts/prompt_templates/msg_prompt_templates"
  HumanMessagePromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/how_to/prompts"
  SystemMessagePromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/how_to/prompts"
  ChatPromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/models/chat/how_to/prompts"
  PromptTemplate:
    documentation: "https://python.langchain.com/docs/modules/model_io/prompts/prompt_templates/"
wrappers:
  RequestsWrapper:
    documentation: ""
  SQLDatabase:
    documentation: ""
output_parsers:
  StructuredOutputParser:
    documentation: "https://python.langchain.com/docs/modules/model_io/output_parsers/structured"
  ResponseSchema:
    documentation: "https://python.langchain.com/docs/modules/model_io/output_parsers/structured"
custom_components:
  CustomComponent:
    documentation: "https://docs.dataformer.ai/guidelines/custom-component"
    # documentation: "https://docs.dataformer.ai/administration/custom-component"
